version: '3'
services: 
    graphite:
        container_name: graphite
        image: graphiteapp/graphite-statsd
        ports: 
            - '8125:8125/udp'
    grafana:
        container_name: grafana
        image: grafana/grafana
        ports: 
            - '3000:3000'
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/config.ini:/etc/grafana/config.ini
        depends_on: 
            - graphite
