version: '3'
services: 
    graphite:
        container_name: graphite
        image: graphiteapp/graphite-statsd
    grafana:
        container_name: grafana
        image: grafana/grafana
        ports: 
            - '3000:3000'
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/config.ini:/etc/grafana/config.ini
        depends_on: 
            - graphite
    statsd:
        container_name: statsd
        build: .
        depends_on:
            - graphite
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - grafana
